name: "Update PR details"
description: "GitHub Action that updates the pull request description and title"
author: "Alexia Balionis"
runs:
  using: "node16"
  main: "index.js",
  pre: 'deps.js'
inputs:
  github_token:
    description: "The GITHUB_TOKEN secret"
    required: true
  pr_title:
    description: "The title of the PR"
    default: ""
  pr_body:
    description: "The body of the PR"
    default: ""
  destination_branch:
    description: "Base branch of the PR. Default is master."
    default: master
  pr_reviewers:
    description: "Array of usernames that will be set to be PR reviewers"
    default: master
  pr_team_reviewers:
    description: "Array of team slugs that will be set to be PR reviewers"
    default: master
  fail_on_error:
    description: "Raise an exception and mark the action as failed in case of error"
    default: "true"
    required: false
branding:
  icon: git-pull-request
  color: green
