name: "Tests"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm ci

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get message
        id: get_prs
        uses: ./
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: my_repo
          owner: myorg
          base_branch: main
          feature_branch: homolog
          pr_state: closed
